name: Print Variable 
on: push
jobs:
  action-var:
    runs-on: ubuntu-latest
    steps:
      - name: Use Env Var
        run: |
          echo "Action var is: ${{vars.APP_MODE}}"
  environment_var:
    runs-on: ubuntu-latest
    env: 
       MY_VAR: ${{vars.APP_MODE}}
    steps:
      - name: Use Action Variable as Environment Context
        run: |
          echo ${{env.MY_VAR}}
        #  echo "Env Var is: $MY_VAR"
          
 
