name: Conditional Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Run install
      run: npm install
    - name: Install dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: Deploy
      run: npm run deploy
      if: github.ref === 'refs/heads/main' && github.event_name === 'push' #On push to only main branch
