name: Matrix Workflow
on: 
  push:
    branches:
      - main    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        node: [18,20]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: Run install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
