name: Event to run on one or more event
on: 
  push:
    branches:
    - main
    - test
    
jobs:
  show-info:
    runs-on: Ubuntu-latest
    steps:
    - name: Info
      run: |
        echo "This will run on specified branch"
