name: Publish image to GHCR
on: 
  push:
    branches:
    - main
jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push the image
        run: |
          docker build . --tag ghcr.io/${{github.repository_owner}}/hello:latest
          docker push ghcr.io/${{github.repository_owner}}/hello:latest
      
