name: Publiash to Github Packages
on: 
  push:
    branches: [main]
jobs:
  build_and_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run install
        run: npm install
#      - name: Install dependencies
#        run: npm ci
      - name: build
        run: npm run build
      - name: Package
        run: npm pack
      - name: Upload
