name: Publish to Github Packages

on:
  push:
    branches: [main]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Build Package
        run: npm run build
      - name: Package the app
        run: npm pack
      - name: Package the App
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [build_and_package]
    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@yashaswinikb18'
      - run: echo "registry=https://npm.pkg.github.com/@solankiarpan" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  
      
