name: Publiash to Github Packages
on: 
  push:
    branches: [main]
jobs:
  build_and_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run install
        run: npm install
#      - name: Install dependencies
#        run: npm ci
      - name: build
        run: npm run build
      - name: Package
        run: npm pack
      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz" #Upload anything with tgz extension
  publish:
    needs: build_and_package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yashaswinikb18'
      - run: echo 'registry==https://npm.pkg.github.com/@yashaswinikb18' > .npmrc
      - name: publish
        run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
